name: Laravel Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, mysql

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Prepare environment
        run: |
          cp .env.example .env.test
          echo "DB_CONNECTION=mysql" >> .env.test
          echo "DB_HOST=127.0.0.1" >> .env.test
          echo "DB_PORT=3306" >> .env.test
          echo "DB_DATABASE=laravel_testing" >> .env.test
          echo "DB_USERNAME=root" >> .env.test
          echo "DB_PASSWORD=root" >> .env.test
          php artisan key:generate --env=test

      - name: Run tests
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel_testing
          DB_USERNAME: root
          DB_PASSWORD: root
        run: |
          php artisan migrate --force
          php artisan test
